# Generated by Django 4.2.4 on 2023-09-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestioner', '0005_tblanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_project',
            },
        ),
    ]
