# Generated by Django 4.2.4 on 2023-09-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestioner', '0006_tblproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblRespondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=50)),
                ('froms', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_respondents',
            },
        ),
    ]
