# Generated by Django 4.2.4 on 2023-09-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestioner', '0008_tblresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField(unique=True)),
                ('respondent_id', models.BigIntegerField(unique=True)),
                ('answer_id', models.IntegerField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'tbl_responses',
            },
        ),
    ]
