# Generated by Django 4.2.4 on 2023-10-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestioner', '0012_delete_tblresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblResponse',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('respondent_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'tbl_response',
            },
        ),
    ]
