# Generated by Django 4.2.4 on 2023-10-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appquestioner', '0013_tblresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblresponse',
            unique_together={('question_id', 'respondent_id')},
        ),
    ]
