# Generated by Django 4.2.4 on 2023-10-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appquestioner', '0016_tblresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblResponse',
        ),
    ]
