# Generated by Django 4.2.4 on 2023-10-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestioner', '0017_delete_tblresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('respondent_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'tbl_response',
                'unique_together': {('question_id', 'respondent_id')},
            },
        ),
    ]
